[build-system]
requires = [
    "setuptools>=30.3.0",
    "cython>=0.29.33",
    "scikit-learn>=1.2.0",
    "numpy>=1.17.3",
    "wheel",
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 120
target-version = ['py310']
skip-string-normalization = true
